name: Mirror to Sourceforge

on:
  push:
    branches-ignore:
      - 'dependabot/**'
      - 'issues/**'
      - 'features/**'
  delete:
  create:

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.GIT_MIRROR_PRIVATE_KEY }}
        with:
          source-repo: 'git@github.com:simpleid/simpleid.git'
          destination-repo: 'ssh://kmo@git.code.sf.net/p/simpleid/code'
